### ISSUE TITLE
Disable prefix not working

### ISSUE THREAD

**Issue by sillen102** [trystan2k/zsh-tab-title#18]
Hi.

I have set the `ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true` in my `.zshrc` but the user and computer name separated by '@' is still showing in the title.

Using v.2.2.0

**Comment by trystan2k** [comment]
Hi @sillen102,

Did you exported the setting ?

You should add like this in the `.zshrc` file:

`export ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true`

Please let me know if this fix the issue.

**Comment by sillen102** [comment]
No it doesn't. The variable is exported. I can even test it in the command line like so:

```
❯ echo $ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX
true
```

What I have done now i simply this:

```bash
if [[ "$ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX" == true ]]; then
  ZSH_TAB_TITLE_PREFIX=""
elif [[ -z "$ZSH_TAB_TITLE_PREFIX" ]]; then
  #ZSH_TAB_TITLE_PREFIX="%n@%m:"
  ZSH_TAB_TITLE_PREFIX=""
fi
```
But this only works for me personally since I'm not interested in having any prefix.
So something isn't working right.

**Comment by sillen102** [comment]
I've also seen that ZSH_TAB_TITLE_ONLY_FOLDER also dosent work right for me. It is displaying the whole path still even though it's set.

I have these set in my .zshrc:

```bash
export ZSH_TAB_TITLE_CONCAT_FOLDER_PROCESS=true
export ZSH_TAB_TITLE_ONLY_FOLDER=true
export ZSH_TAB_TITLE_ENABLE_FULL_COMMAND=true
export ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true
```

**Comment by trystan2k** [comment]
Hi @sillen102,

Strange. I have tested it before send the previous reply, and it worked for me. 

What terminal and OS are you using ? 

Because I am using Hyper.js and indeed in this terminal I do not see the prefix (it only shows me the current directory I am in) with the setting setup or not, but using Mac OS Terminal.app, the setting works fine.

**Comment by sillen102** [comment]
I'm running Debian 11 Bullseye and using GNOME-Terminal

**Comment by trystan2k** [comment]
Ok. I will install it in a virtual machine and try to reproduce it, because as I said, in Mac OS Termina.app is working fine.

I will let you know when I have some news on this.

**Comment by sillen102** [comment]
The strange part is that I am running `oh-my-zsh` and installing it didn't work. It couldn't find the plugin until I changed the name of the folder from `zsh-tab-title` to simply `title`. I guess it's because the name of the zsh-file is `title.plugin.zsh`?

So far from what I can see the only thing working for me is `export ZSH_TAB_TITLE_CONCAT_FOLDER_PROCESS=true` because it actually does show the folder and the command when I run something.

**Comment by sillen102** [comment]
I'm on my working machine now (with Debian). But I will try it on my MacBook later tonight as well.

**Comment by sillen102** [comment]
I just tried something that might have fixed it. I reinstalled and didn't move the folder from `.oh-my-zsh/custom/plugins/zsh-tab-title` to `.oh-my-zsh/custom/plugins/title`. Instead I renamed the file from `title.plugin.zsh` to `zsh-tab-title.plugin.zsh` (to fix the plugin not found error). And now it works!

However I am still confused about the `ZSH_TAB_TITLE_ONLY_FOLDER` becase it is till showing the whole path and not just the last folder.

**Comment by trystan2k** [comment]
Great. I think I didn't test with oh-my-zsh. I will take a look and update the documentation, if needed.

About the `ZSH_TAB_TITLE_ONLY_FOLDER `, still see it works for me in Terminal.app at Mac OS the only strange thing is that it show the folder 2 times, one complete and one just the folder.

If you execute this command in terminal `${PWD##*/}` does it show the folder name (only the folder name, not complete path) ?

**Comment by sillen102** [comment]
It does. It does show just the folder name when I run the command. Like so:

```
/etc/systemd/system🔒 
❯ echo ${PWD##*/}
system
```

However the title still shows the full path. 

![image](https://user-images.githubusercontent.com/44360609/128304041-e2013471-b743-4f8e-bd69-108b51f49bc0.png)

**Comment by sillen102** [comment]
I even tried editing the part with the `ZSH_TAB_TITLE_ONLY_FOLDER` like so:

```bash
  if [[ "$ZSH_TAB_TITLE_ONLY_FOLDER" == true ]]; then
    #ZSH_THEME_TERM_TAB_TITLE_IDLE=${PWD##*/}
    ZSH_THEME_TERM_TAB_TITLE_IDLE="SOME TEXT"
  fi

  ZSH_THEME_TERM_TAB_TITLE_IDLE="SOME TEXT"
```

It still shows the full path. It's as if it's being overridden by something. I wonder if it's something inside `./oh-my-zsh/oh-my-zsh.sh` that is being sourced. I have not altered this file at all though so it's the one from the oh-my-zsh repo.

The variable is set and as you can see I also tried setting `ZSH_THEME_TERM_TAB_TITLE_IDLE` outside of the if-statemen but even that didn't work.

```
❯ echo $ZSH_TAB_TITLE_ONLY_FOLDER         
true
```

**Comment by trystan2k** [comment]
Ok, I think I found what is going on.

Seems like gnome-terminal does not let to set different texts to terminal title and tabs, and the zsh-tab-title use this functionality in other terminals.

For example,  `ZSH_TAB_TITLE_ONLY_FOLDER` only works to show the folder in tab title (while in window it still show the full folder):
![image](https://user-images.githubusercontent.com/447294/128331947-57227be2-eb5a-49f1-8e78-2591edd6310e.png)

That is why it is 'not working' for you, because you are seeing is the window title, always.

The solution for these case could be to check if it is the gnome-terminal and if so, set both information (which we would set to window and tab) into one string (concatenating it) and set as window title. That way all settings will work as expected, and you will see correctly the data.

I will see if I get some time over the weekend and do this change in a branch and let you know, so you can test and see what do you think and if it is all good, I can release a new version.

What do you think ?

**Comment by sillen102** [comment]
Sure I'd be willing to try it out!

**Comment by trystan2k** [comment]
Hi @sillen102,

I made a initial attempt to fix this for gnome_terminal, could you please test and see if it works as expected for you ?

You can copy the code from here: https://github.com/trystan2k/zsh-tab-title/blob/feature/gnome_adjusts/zsh-tab-title.plugin.zsh and paste it into your installed plugin file.

Please let me know if you have any question and how it goes!

**Comment by sillen102** [comment]
Hi. Great, thanks. I will test it. I am on vacation at the moment though and don't have access to my work computer. I will do it next week and get back to you.

**Comment by trystan2k** [comment]
Don't worry, **enjoy your vacations** and when you are back and able to test, just let me know the results!

**Comment by trystan2k** [comment]
Hi @sillen102,

Did you get a chance to test if the change solve your case ?

Thanks !

**Comment by sillen102** [comment]
Hi.

I just tested it and it does not work.

**Comment by mattthym** [comment]
Hey @trystan2k,

Unfortunately I ran into the same issue. I've used your plugin for a while, but have to report that disabling the prefix indeed does not work like expected.

I'm running `zsh` in `kitty`. Initially I loaded your plugin using `zgenom`, but to make sure I am able to reproduce the issue, I did the following:

- Launch terminal emulator `kitty`
  Terminal tab is set to "zsh"
  ZSH_TAB_TITLE_PREFIX is unset
- Source the plugin manually by running `source .../zsh-tab-title.plugin.zsh`
  Terminal tab is set to "USER@HOST: FULL_PATH"
  ZSH_TAB_TITLE_PREFIX got set to "%n@%m:" by plugin
- Run `export ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true`
  Terminal tab title does not change
- Run `export ZSH_TAB_TITLE_ONLY_FOLDER=true`
  Terminal tab title does not change
  
Running `export ZSH_TAB_TITLE_CONCAT_FOLDER_PROCESS=true` or `export ZSH_TAB_TITLE_ENABLE_FULL_COMMAND=true` both work and result in the expected tab title when running a command.

I can disable the prefix if I launch it like this:
```sh
ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
# or
export ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true && source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
```

For whatever reason this does not work for `ZSH_TAB_TITLE_ONLY_FOLDER`...

If I echo the value of variable `tabTitle` used in the title function, by inserting `echo $1` on line 18 in the plugin, I can observe whether the assignment works correctly.
- Trying to set it like this assigns the variable correctly:
  ```sh
  export ZSH_TAB_TITLE_ONLY_FOLDER=true && source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
  ```
  It prints only the folder of the cwd like expected. However, the tab title is not set to it. This might be a bug in kitty though....perhaps @sillen102 or someone else could try it in a different terminal emulator.
- Trying to set it like this does not:
  ```sh
  ZSH_TAB_TITLE_ONLY_FOLDER=true source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
  ```
  It prints "%20<..<%~%<<"

**Comment by totoroot** [comment]
Hey @trystan2k,

Unfortunately I ran into the same issue. I've used your plugin for a while, but have to report that disabling the prefix indeed does not work like expected.

I'm running `zsh` in `kitty`. Initially I loaded your plugin using `zgenom`, but to make sure I am able to reproduce the issue, I did the following:

- Launch terminal emulator `kitty`
  Terminal tab is set to "zsh"
  ZSH_TAB_TITLE_PREFIX is unset
- Source the plugin manually by running `source .../zsh-tab-title.plugin.zsh`
  Terminal tab is set to "USER@HOST: FULL_PATH"
  ZSH_TAB_TITLE_PREFIX got set to "%n@%m:" by plugin
- Run `export ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true`
  Terminal tab title does not change
- Run `export ZSH_TAB_TITLE_ONLY_FOLDER=true`
  Terminal tab title does not change
  
Running `export ZSH_TAB_TITLE_CONCAT_FOLDER_PROCESS=true` or `export ZSH_TAB_TITLE_ENABLE_FULL_COMMAND=true` both work and result in the expected tab title when running a command.

I can disable the prefix if I launch it like this:
```sh
ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
# or
export ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true && source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
```

For whatever reason this does not work for `ZSH_TAB_TITLE_ONLY_FOLDER`...

If I echo the value of variable `tabTitle` used in the title function, by inserting `echo $1` on line 18 in the plugin, I can observe whether the assignment works correctly.
- Trying to set it like this assigns the variable correctly:
  ```sh
  export ZSH_TAB_TITLE_ONLY_FOLDER=true && source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
  ```
  It prints only the folder of the cwd like expected.
  However, the tab title still does not get set to it. This might be a bug in kitty though....perhaps @sillen102 or someone else could try it in a different terminal emulator.
- Trying to set it like this does not:
  ```sh
  ZSH_TAB_TITLE_ONLY_FOLDER=true source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
  ```
  It prints "%20<..<%~%<<"

**Comment by trystan2k** [comment]
> Hey @trystan2k,
> 
> Unfortunately I ran into the same issue. I've used your plugin for a while, but have to report that disabling the prefix indeed does not work like expected.
> 
> I'm running `zsh` in `kitty`. Initially I loaded your plugin using `zgenom`, but to make sure I am able to reproduce the issue, I did the following:
> 
> * Launch terminal emulator `kitty`
>   Terminal tab is set to "zsh"
>   ZSH_TAB_TITLE_PREFIX is unset
> * Source the plugin manually by running `source .../zsh-tab-title.plugin.zsh`
>   Terminal tab is set to "USER@HOST: FULL_PATH"
>   ZSH_TAB_TITLE_PREFIX got set to "%n@%m:" by plugin
> * Run `export ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true`
>   Terminal tab title does not change
> * Run `export ZSH_TAB_TITLE_ONLY_FOLDER=true`
>   Terminal tab title does not change
> 
> Running `export ZSH_TAB_TITLE_CONCAT_FOLDER_PROCESS=true` or `export ZSH_TAB_TITLE_ENABLE_FULL_COMMAND=true` both work and result in the expected tab title when running a command.
> 
> I can disable the prefix if I launch it like this:
> 
> ```shell
> ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
> # or
> export ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true && source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
> ```
> 
> For whatever reason this does not work for `ZSH_TAB_TITLE_ONLY_FOLDER`...
> 
> If I echo the value of variable `tabTitle` used in the title function, by inserting `echo $1` on line 18 in the plugin, I can observe whether the assignment works correctly.
> 
> * Trying to set it like this assigns the variable correctly:
>   ```shell
>   export ZSH_TAB_TITLE_ONLY_FOLDER=true && source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   It prints only the folder of the cwd like expected.
>   However, the tab title still does not get set to it. This might be a bug in kitty though....perhaps @sillen102 or someone else could try it in a different terminal emulator.
> * Trying to set it like this does not:
>   ```shell
>   ZSH_TAB_TITLE_ONLY_FOLDER=true source ~/.zgenom/sources/trystan2k/zsh-tab-title/___/zsh-tab-title.plugin.zsh
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   It prints "%20<..<%~%<<"

Hi @totoroot ,

Thanks for such detailed report !

I will try to look into it in the next days and get back to you if I find the solution to this problem.

One question though, are you using which OS ? Linux, Mac, Windows ... ?

**Comment by totoroot** [comment]
No worries, I still get good use out of your plugin, so no need to hurry.
I tried to find the issue myself, but couldn't and thought you might know better what could be the reason.

I'm using NixOS, so Linux. If it helps, I could check if I encounter the same issue on macOS.
As far as I remember it was just the same with zsh in kitty.

Thanks for looking into it!

**Comment by trystan2k** [comment]
> https://github.com/trystan2k/zsh-tab-title/blob/feature/gnome_adjusts/zsh-tab-title.plugin.zsh

Hi @totoroot ,

I think I found the issue. 

The main problem was that some of the environment variables were only been take into account when you open a new terminal. If you export a env variable after that, it does not read it again so it does not take effect. 

I have changed that so it will take check all variables when the title is about to change back to idle state.

Could you please test the code I pushed to this branch and let me know if it now works ? https://github.com/trystan2k/zsh-tab-title/tree/feature/fix-env-load

Let me know if it works and if so, I do a release with this fix.

Thanks

**Comment by trystan2k** [comment]
It could also fix your problems @sillen102 , if you still use the plugin and could take a look.

**Comment by Leokuma** [comment]
Regarding `ZSH_TAB_TITLE_ONLY_FOLDER` on GNOME Terminal, I changed one line in `zsh-tab-title.plugin.zsh` and it's now working as **I** wanted. The tab title is always the same as the window title.

https://github.com/user-attachments/assets/3ff997e2-d8dd-4b58-b44a-0447cd2d5daa

**Comment by Leokuma** [comment]
Regarding `ZSH_TAB_TITLE_ONLY_FOLDER` on GNOME Terminal, I changed one line in `zsh-tab-title.plugin.zsh` and it's now working as I personally wanted. The tab title is always the same as the window title.

https://github.com/user-attachments/assets/e3b011a2-1c08-45ca-a609-bec64bddfa6a

**Comment by trystan2k** [comment]
> Regarding `ZSH_TAB_TITLE_ONLY_FOLDER` on GNOME Terminal, I changed one line in `zsh-tab-title.plugin.zsh` and it's now working as I personally wanted. The tab title is always the same as the window title.
> 
>  2024-09-20.13-18-32.mp4

Nice !

Yeah, seems that some terminals does not allow to have both setup independently (tab and window) or the way it is done, is not correct for them.

Once I get some time I will try to look into this, to see if it is possible or not.
