### ISSUE TITLE
zsh-tab-title plugin not found

### ISSUE THREAD

**Issue by declan-fitzpatrick** [trystan2k/zsh-tab-title#19]
I am using zsh and oh-my-zsh. 
Following your installation guide leads to an error with oh-my-zsh.

> Execute `git clone https://github.com/trystan2k/zsh-tab-title ~/.oh-my-zsh/custom/plugins/zsh-tab-title`. Add `zsh-tab-title` into plugins array in `.zshrc`

The error is: `[oh-my-zsh] plugin 'zsh-tab-title' not found`

I corrected the issue by renaming [`title.plugin.zsh`](https://github.com/trystan2k/zsh-tab-title/blob/master/title.plugin.zsh) to `zsh-tab-title.plugin.zsh` and then it works as expected.

**Comment by trystan2k** [comment]
Hi @declan-fitzpatrick,

Thanks for the issue !

I realize that I had the same problem, and I had locally changed the name of the file and forgot to commit it. 🤦‍♂️.

I have just pushed this change to the repo. 

Please let me know if it works as expected or if you see any other issue.

Thanks again !

**Comment by declan-fitzpatrick** [comment]
Looks good. 

Your ci-workflow is now no longer correct [`path: "shellcheck.sh,title.plugin.zsh"`](https://github.com/trystan2k/zsh-tab-title/blob/b95169b0ce5240da11a5eb78d6cf343c923ddd2e/.github/workflows/ci-workflow.yaml#L17), which is making your [GitHub action fail silently](https://github.com/trystan2k/zsh-tab-title/runs/3793187120?check_suite_focus=true#step:4:11).

**Comment by trystan2k** [comment]
Oh yes, did the thing too quickly and didn't look into this.

Thanks a lot !!

**Comment by declan-fitzpatrick** [comment]
Issue resolved in [Release v2.3.1](https://github.com/trystan2k/zsh-tab-title/releases/tag/v2.3.1).
